trigger:
- main

pr: none

pool:
  vmImage: 'ubuntu-latest'


variables:
- group: NugetDeployment

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore projects'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build projects'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run tests and report to ADO'
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--collect "Code coverage"'
