trigger:
  branches:
    exclude:
    - "*"

pr:
- main

pool:
  vmImage: 'ubuntu-latest'


variables:
- group: NugetDeployment

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore projects'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build projects'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run tests and report to ADO'
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--collect "Code coverage"'

- powershell: "dotnet pack \".\\PiLed\\PiLed.csproj\" -c Release -o nupkgs --version-suffix \"-beta-$(Build.BuildNumber)\""
  displayName: "Build PiLed nuget package"

- powershell: "ls nupkgs"
  displayName: "List contents of nupkgs"

- powershell: |
    Get-ChildItem nupkgs |
    Foreach-Object {
    dotnet nuget push $_.FullName --api-key ${NugetApiKey} --source https://api.nuget.org/v3/index.json
    }
  displayName: "Deploy Packages to nuget"